package com.concredito.clientes.ui.theme

import androidx.compose.ui.graphics.Color

val finaCreditoThemeLightPrimary = Color(0xFF006D30)
val finaCreditoThemeLightOnPrimary = Color(0xFFFFFFFF)
val finaCreditoThemeLightPrimaryContainer = Color(0xFF84FB9D)
val finaCreditoThemeLightOnPrimaryContainer = Color(0xFF00210A)
val finaCreditoThemeLightSecondary = Color(0xFF6D5E00)
val finaCreditoThemeLightOnSecondary = Color(0xFFFFFFFF)
val finaCreditoThemeLightSecondaryContainer = Color(0xFFFFE24E)
val finaCreditoThemeLightOnSecondaryContainer = Color(0xFF211B00)
val finaCreditoThemeLightTertiary = Color(0xFF006D30)
val finaCreditoThemeLightOnTertiary = Color(0xFFFFFFFF)
val finaCreditoThemeLightTertiaryContainer = Color(0xFF84FB9D)
val finaCreditoThemeLightOnTertiaryContainer = Color(0xFF00210A)
val finaCreditoThemeLightError = Color(0xFFBA1A1A)
val finaCreditoThemeLightErrorContainer = Color(0xFFFFDAD6)
val finaCreditoThemeLightOnError = Color(0xFFFFFFFF)
val finaCreditoThemeLightOnErrorContainer = Color(0xFF410002)
val finaCreditoThemeLightBackground = Color(0xFFF8FDFF)
val finaCreditoThemeLightOnBackground = Color(0xFF001F25)
val finaCreditoThemeLightSurface = Color(0xFFF8FDFF)
val finaCreditoThemeLightOnSurface = Color(0xFF001F25)
val finaCreditoThemeLightSurfaceVariant = Color(0xFFDDE5DA)
val finaCreditoThemeLightOnSurfaceVariant = Color(0xFF414941)
val finaCreditoThemeLightOutline = Color(0xFF727970)
val finaCreditoThemeLightInverseOnSurface = Color(0xFFD6F6FF)
val finaCreditoThemeLightInverseSurface = Color(0xFF00363F)
val finaCreditoThemeLightInversePrimary = Color(0xFF67DE84)
val finaCreditoThemeLightShadow = Color(0xFF000000)
val finaCreditoThemeLightSurfaceTint = Color(0xFF006D30)
val finaCreditoThemeLightOutlineVariant = Color(0xFFC1C9BE)
val finaCreditoThemeLightScrim = Color(0xFF000000)

val finaCreditoThemeDarkPrimary = Color(0xFF67DE84)
val finaCreditoThemeDarkOnPrimary = Color(0xFF003916)
val finaCreditoThemeDarkPrimaryContainer = Color(0xFF005323)
val finaCreditoThemeDarkOnPrimaryContainer = Color(0xFF84FB9D)
val finaCreditoThemeDarkSecondary = Color(0xFFE4C600)
val finaCreditoThemeDarkOnSecondary = Color(0xFF393000)
val finaCreditoThemeDarkSecondaryContainer = Color(0xFF524600)
val finaCreditoThemeDarkOnSecondaryContainer = Color(0xFFFFE24E)
val finaCreditoThemeDarkTertiary = Color(0xFF67DE84)
val finaCreditoThemeDarkOnTertiary = Color(0xFF003916)
val finaCreditoThemeDarkTertiaryContainer = Color(0xFF005323)
val finaCreditoThemeDarkOnTertiaryContainer = Color(0xFF84FB9D)
val finaCreditoThemeDarkError = Color(0xFFFFB4AB)
val finaCreditoThemeDarkErrorContainer = Color(0xFF93000A)
val finaCreditoThemeDarkOnError = Color(0xFF690005)
val finaCreditoThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val finaCreditoThemeDarkBackground = Color(0xFF001F25)
val finaCreditoThemeDarkOnBackground = Color(0xFFFFFFFF)
val finaCreditoThemeDarkSurface = Color(0xFF001F25)
val finaCreditoThemeDarkOnSurface = Color(0xFFFFFFFF)
val finaCreditoThemeDarkSurfaceVariant = Color(0xFF414941)
val finaCreditoThemeDarkOnSurfaceVariant = Color(0xFFC1C9BE)
val finaCreditoThemeDarkOutline = Color(0xFF8B9389)
val finaCreditoThemeDarkInverseOnSurface = Color(0xFF001F25)
val finaCreditoThemeDarkInverseSurface = Color(0xFFA6EEFF)
val finaCreditoThemeDarkInversePrimary = Color(0xFF006D30)
val finaCreditoThemeDarkShadow = Color(0xFF000000)
val finaCreditoThemeDarkSurfaceTint = Color(0xFF67DE84)
val finaCreditoThemeDarkOutlineVariant = Color(0xFF414941)
val finaCreditoThemeDarkScrim = Color(0xFF000000)

val seed = Color(0xFF009444)
